CREATE TABLE transfers
(
    id                  UUID PRIMARY KEY                  DEFAULT gen_random_uuid(),
    transaction_id      UUID                     NOT NULL UNIQUE,
    record_type         VARCHAR(20),
    service_id          UUID,
    transaction_status  VARCHAR(30)              NOT NULL,
    internal_status     VARCHAR(30),
    internal_message    VARCHAR(512),
    country_code        VARCHAR(3),
    account_number      VARCHAR(64),
    sender_comment      VARCHAR(140),
    settlement_amount   NUMERIC(16, 2),
    settlement_currency VARCHAR(3),
    withdraw_amount     NUMERIC(16, 2),
    withdraw_currency   VARCHAR(3),
    fee_amount          NUMERIC(16, 2),
    fee_currency        VARCHAR(3),
    rate                NUMERIC(20, 10),
    transaction_date    TIMESTAMP WITH TIME ZONE,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    middle_name         VARCHAR(255),
    birth_date          DATE,
    phone               VARCHAR(30),
    sender_first_name   VARCHAR(255),
    sender_last_name    VARCHAR(255),
    sender_middle_name  VARCHAR(255),
    sender_birth_date   VARCHAR(32),
    sender_full_address VARCHAR(512),
    sender_country      VARCHAR(3),
    sender_state        VARCHAR(255),
    sender_city         VARCHAR(255),
    sender_street       VARCHAR(255),
    sender_zip          VARCHAR(20),
    coinpay_transfer_id UUID,
    status_message      VARCHAR(255),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
